import React, { useState, useEffect, useRef } from 'react';
import { ExternalLink, Github, Star, Calendar, ArrowRight } from 'lucide-react';

function ProjectsPage() {
  const [activeProject, setActiveProject] = useState(0);
  const containerRef = useRef(null);
  const projectRefs = useRef([]);

  const projects = [
    {
      id: 1, title: "AI Tour Planner",
      description: "Personalized travel itineraries powered by Gemini AI, Maps, and real-time flight data.",
      longDescription: "An immersive travel planning application leveraging Gemini AI and third-party APIs. Plan trips, explore destinations with real-time maps, view relevant imagery, and book flights — all while storing trip data securely using Firebase.",
      tech: ["React Native","Firebase","Firestore","Firebase Auth","Google Maps API","Pixabay API","Gemini AI"],
      status: "Live", githubStars: "18 stars", lastUpdated: "2024",
      image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/ai-tour-planner",
      gradient: "linear-gradient(160deg, rgb(7,14,87) 0%, rgb(41,50,203) 60%, rgb(121,128,255) 85%)",
      textColor: "#a8c8ff", shadowColor: "#2932CB",
      features: ["AI-generated personalized travel itineraries.","Flight booking integration.","Google Maps API destinations.","Activity imagery via Pixabay.","Firebase auth & storage."]
    },
    {
      id: 2, title: "AI Video Generator",
      description: "Text prompt → rendered 1080p video via serverless async pipeline.",
      longDescription: "AI Video Gen streamlines video creation using AI and serverless tools. Next.js and Remotion let users generate visuals from prompts. Convex and Firebase power real-time backend; Inngest manages background rendering.",
      tech: ["Next.js","Convex","Remotion","Firebase","Inngest","Tailwind CSS"],
      status: "Beta", githubStars: "12 stars", lastUpdated: "2024",
      image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/ai-video-gen",
      gradient: "linear-gradient(160deg, rgb(19,78,74) 0%, rgb(20,184,166) 60%, rgb(94,234,212) 85%)",
      textColor: "#a0f0e8", shadowColor: "#14B8A6",
      features: ["AI-based video generation.","Serverless Convex backend.","Automated workflows via Inngest.","Frame-accurate Remotion rendering.","Firebase auth & cloud storage."]
    },
    {
      id: 3, title: "Authentiq",
      description: "AI text authenticity detector — GPT-2 + DeBERTa ensemble with 85%+ accuracy.",
      longDescription: "An AI-powered tool that classifies whether text was written by a human or generated by AI. Built on a GPT-2 + DeBERTa ensemble model achieving 85%+ classification accuracy, plus a semantic plagiarism engine using SentenceTransformers that reduced similarity search latency by 40%.",
      tech: ["React.js","FastAPI","Python","HuggingFace","DeBERTa","SentenceTransformers"],
      status: "Live", githubStars: "21 stars", lastUpdated: "2025",
      image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/authentiq",
      gradient: "linear-gradient(160deg, rgb(10,45,80) 0%, rgb(20,100,180) 60%, rgb(80,160,240) 85%)",
      textColor: "#a8d0f8", shadowColor: "#1464B4",
      features: ["85%+ accuracy via GPT-2 + DeBERTa ensemble.","Semantic plagiarism engine with SentenceTransformers.","40% reduction in similarity search latency.","FastAPI async inference backend.","Clean React frontend for instant results."]
    },
    {
      id: 4, title: "Book Store",
      description: "Platform for discovering and exploring regional literature.",
      longDescription: "Online platform where users explore, manage, and engage with regional books. Clean, intuitive interface promoting local literature to a wider audience.",
      tech: ["React.js","Tailwind CSS","Express.js","MongoDB","Firebase"],
      status: "Featured", githubStars: "24 stars", lastUpdated: "2024",
      image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/book-Store",
      gradient: "linear-gradient(160deg, rgb(107,13,51) 0%, rgb(219,39,119) 60%, rgb(244,114,182) 85%)",
      textColor: "#ffb0d8", shadowColor: "#DB2777",
      features: ["Browse regional books by category.","Minimalist, focused UI.","Optimized performance."]
    },
    {
      id: 5, title: "Demand Forecasting System",
      description: "Hybrid SARIMA + LSTM model for Indian retail demand prediction — ~87% MAPE accuracy.",
      longDescription: "Hybrid ML forecasting combining SARIMA (statistical) with LSTM (deep learning) to predict demand for Indian SME retailers. Achieved 87% MAPE accuracy on a real-world retail dataset of 20k+ records. Simulated inventory policies showed ~20% reduction in overstock events.",
      tech: ["Python","SARIMA","LSTM","Keras","TensorFlow","Pandas","NumPy","Matplotlib"],
      status: "Research", githubStars: "8 stars", lastUpdated: "2024",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/demand-forecasting",
      gradient: "linear-gradient(160deg, rgb(30,27,75) 0%, rgb(99,102,241) 60%, rgb(147,197,253) 85%)",
      textColor: "#c4b5fd", shadowColor: "#6366F1",
      features: ["Hybrid SARIMA + LSTM pipeline.","87% MAPE accuracy on 20k+ records.","~20% reduction in overstock events.","Modular folder structure.","Inventory optimization output."]
    },
    {
      id: 6, title: "AI Website Builder",
      description: "Natural language → fully responsive website layout.",
      longDescription: "AI-first web builder where users generate responsive layouts from plain text prompts. Next.js App Router + Convex backend maps AI-generated output to prebuilt React components and Tailwind styles instantly.",
      tech: ["Next.js","TailwindCSS","Firebase","Convex","Vercel"],
      status: "Beta", githubStars: "9 stars", lastUpdated: "2025",
      image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&q=80",
      githubUrl: "https://github.com/Ankith-sara/AI-website-Builder",
      gradient: "linear-gradient(160deg, rgb(61,26,122) 0%, rgb(126,34,206) 60%, rgb(192,132,252) 85%)",
      textColor: "#e9d5ff", shadowColor: "#7E22CE",
      features: ["Instant page generation from prompts.","Prebuilt UI components via AI.","Real-time Convex backend.","Optimized Vercel deployments.","Clean Next.js App Router architecture."]
    }
  ];

  useEffect(() => {
    const container = containerRef.current;
    if (!container || window.innerWidth < 1024) return;
    const handleScroll = () => {
      const center = container.getBoundingClientRect().top + container.clientHeight / 2;
      let closest = 0, minDist = Infinity;
      projectRefs.current.forEach((ref, i) => {
        if (!ref) return;
        const d = Math.abs(ref.getBoundingClientRect().top + ref.getBoundingClientRect().height / 2 - center);
        if (d < minDist) { minDist = d; closest = i; }
      });
      if (activeProject !== closest) setActiveProject(closest);
    };
    container.addEventListener('scroll', handleScroll, { passive: true });
    handleScroll();
    return () => container.removeEventListener('scroll', handleScroll);
  }, [activeProject]);

  const statusColors = {
    "Featured": "rgba(250,204,21,", "Live": "rgba(74,222,128,",
    "Beta": "rgba(96,165,250,", "Research": "rgba(192,132,252,",
  };

  const StatusBadge = ({ status }) => {
    const c = statusColors[status] || "rgba(148,163,184,";
    return (
      <span className="px-3 py-1 text-xs font-mono rounded-full"
        style={{ background: `${c}0.08)`, color: `${c}0.9)`, border: `1px solid ${c}0.2)` }}>
        {status}
      </span>
    );
  };

  const current = projects[activeProject];

  return (
    <div className="min-h-screen text-white relative overflow-hidden">
      {/* Floating particles */}
      <div className="absolute inset-0 pointer-events-none">
        {[...Array(40)].map((_, i) => (
          <div key={i} className="absolute w-1 h-1 rounded-full"
            style={{
              top: `${Math.random() * 100}%`,
              left: `${Math.random() * 100}%`,
              background: 'rgba(0,212,255,0.3)',
              animation: `float ${8 + Math.random() * 8}s linear infinite`,
              animationDelay: `${Math.random() * 8}s`
            }} />
        ))}
      </div>

      <div className="relative z-20 px-4 pt-28 pb-12 md:pt-36 md:pb-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16 md:mb-20">
            <p className="font-mono text-xs tracking-widest text-slate-600 uppercase mb-3">Portfolio Showcase</p>
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-display font-black text-white mb-6 leading-tight">
              Featured <span className="grad-text">Projects</span>
            </h1>
            <p className="text-slate-500 text-base font-mono leading-relaxed max-w-2xl mx-auto">
              Web apps, AI systems, and digital experiences — each built to solve a real problem.
            </p>
          </div>

          <section className="relative">
            <div className="relative mx-auto lg:flex lg:items-start w-full gap-8">
              <div ref={containerRef}
                className="lg:w-[60%] lg:max-h-[91vh] lg:overflow-y-auto lg:scroll-smooth"
                style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>

                {projects.map((project, index) => (
                  <div key={project.id} ref={(el) => (projectRefs.current[index] = el)} className="mb-16 lg:mb-24">
                    <div className="relative cursor-pointer overflow-hidden rounded-3xl p-1 shadow-2xl"
                      style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)' }}>
                      <div className="group relative flex flex-col items-center justify-between overflow-hidden rounded-2xl lg:h-[520px]" style={{ minHeight: '260px' }}>
                        <div className="absolute inset-0 -z-10" style={{ background: project.gradient }} />
                        <div className="hidden lg:flex w-full flex-row items-start justify-between px-10 py-7 gap-4">
                          <h3 className="text-xl font-display font-bold max-w-[85%] leading-snug" style={{ color: project.textColor }}>
                            {project.description}
                          </h3>
                          <ArrowRight className="size-5 flex-shrink-0 mt-1" style={{ color: project.textColor }} />
                        </div>
                        <img alt={project.title} src={project.image}
                          className="w-full max-w-[86%] translate-y-5 rounded-t-xl border border-white/15 transition-all duration-500 will-change-transform lg:group-hover:scale-[1.06] lg:group-hover:-rotate-2 object-cover"
                          style={{ boxShadow: `0 0 40px ${project.shadowColor}60, 0 20px 60px rgba(0,0,0,0.5)`, height: '320px' }}
                          loading="lazy" />
                      </div>
                    </div>

                    <div className="p-4 lg:hidden">
                      <div className="flex flex-wrap items-center gap-3 mt-4 mb-3">
                        <h3 className="text-white text-2xl font-display font-black">{project.title}</h3>
                        <StatusBadge status={project.status} />
                      </div>
                      <p className="text-slate-400 my-4 text-sm leading-relaxed font-mono">{project.longDescription}</p>
                      <div className="flex flex-wrap gap-2 mb-6">
                        {project.tech.map(t => <span key={t} className="space-tag px-3 py-1 rounded-lg">{t}</span>)}
                      </div>
                      <div className="flex gap-4">
                        <a href={project.githubUrl} target="_blank" rel="noopener noreferrer"
                          className="flex-1 flex items-center gap-2 justify-center px-5 py-2.5 rounded-xl font-display text-sm font-bold text-black"
                          style={{ background: 'rgba(255,255,255,0.9)' }}>
                          <ExternalLink className="w-4 h-4" />View
                        </a>
                        <a href={project.githubUrl} target="_blank" rel="noopener noreferrer"
                          className="glass-btn-outline flex-1 flex items-center gap-2 justify-center px-5 py-2.5 rounded-xl font-display text-sm font-bold text-white">
                          <Github className="w-4 h-4" />Code
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Sticky panel */}
              <div className="hidden lg:block lg:w-[40%] lg:sticky lg:top-24 h-fit">
                {current && (
                  <div className="glass-card ice-shimmer rounded-3xl p-7 transition-all duration-500">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-1.5 h-8 rounded-full" style={{ background: current.shadowColor, boxShadow: `0 0 12px ${current.shadowColor}` }} />
                      <h3 className="text-white text-2xl font-display font-black">{current.title}</h3>
                      <StatusBadge status={current.status} />
                    </div>
                    <p className="text-slate-400 text-sm leading-relaxed font-mono mb-5">{current.longDescription}</p>
                    <h4 className="font-mono text-xs uppercase tracking-wider mb-3" style={{ color: 'rgba(160,215,255,0.5)' }}>Features</h4>
                    <ul className="space-y-2 mb-6">
                      {current.features.map((f, i) => (
                        <li key={i} className="flex items-start gap-2 font-mono text-slate-400" style={{ fontSize: '0.78rem' }}>
                          <div className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: current.shadowColor }} />
                          {f}
                        </li>
                      ))}
                    </ul>
                    <div className="flex flex-wrap gap-2 mb-6">
                      {current.tech.map(t => <span key={t} className="space-tag px-3 py-1 rounded-lg">{t}</span>)}
                    </div>
                    <div className="flex items-center gap-5 mb-6 font-mono text-xs text-slate-600">
                      <div className="flex items-center gap-1.5"><Star className="w-3.5 h-3.5 text-yellow-500" />{current.githubStars}</div>
                      <div className="flex items-center gap-1.5"><Calendar className="w-3.5 h-3.5" />{current.lastUpdated}</div>
                    </div>
                    <div className="flex gap-3">
                      <a href={current.githubUrl} target="_blank" rel="noopener noreferrer"
                        className="flex-1 flex items-center gap-2 justify-center px-5 py-2.5 rounded-xl font-display text-sm font-bold text-black"
                        style={{ background: 'rgba(255,255,255,0.9)' }}>
                        <ExternalLink className="w-4 h-4" />View
                      </a>
                      <a href={current.githubUrl} target="_blank" rel="noopener noreferrer"
                        className="glass-btn-outline flex-1 flex items-center gap-2 justify-center px-5 py-2.5 rounded-xl font-display text-sm font-bold text-white">
                        <Github className="w-4 h-4" />Code
                      </a>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

export default ProjectsPage;
